# This is a basic workflow to help you get started with Actions

name: Artifacts

# Controls when the workflow will run
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Npm install
        run: npm ci
        working-directory: ./site

      - name: Pull notion data
        run: |
          export NOTION_KEY=${{ secrets.NOTION_KEY }};
          export NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }};
          npm run notion:pull
        working-directory: ./site

      - name: Build App
        run: npm run build
        working-directory: ./site

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip and Deploy static site to S3 bucket
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          tar -czf $TAG_NAME.tar.gz -C ./out .
          aws s3 cp ./$TAG_NAME.tar.gz s3://${{ secrets.AWS_S3_BUCKET_ARTIFACT_NAME }}/
        working-directory: ./site
